#Path properties
settings:
  uploadDirectory: "dlibraUpload/"
  downloadDirectory: "dlibraDownload/"
  pathToDLibraScript: "/dlibra-cmdln-tools"

  songDataStorage: "audioFilesStorage/"
  vampPath: "/usr/lib/"

  #Converters properties
  defaultDivisions: 4
  defaultBpm: 120
  defaultBeats: 4
  defaultBeatType: 4
  maxNotesInLineAbc: 20

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

musicxml:
  useBassKey: false
  useDots: false
  useRest: true

  delete16thRest: false
  delete16thPitch: false
