#Path properties
settings:
  uploadDirectory: "dlibraUpload/"
  downloadDirectory: "dlibraDownload/"
  pathToDLibraScript: "/dlibra-cmdln-tools"

  songDataStorage: "audioFilesStorage/"
  vampPath: "/usr/lib/"

#Converters properties
  defaultDivisions: 4
  defaultBpm: 120
  defaultBeats: 4
  defaultBeatType: 4

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB